Fix renderings of "changes" warning on both slides and html
Since creating a new slides with inline-content set to true trigger the
following error:

  AssertionError: Losing "classes" attribute: ['admonition-']

This commit duplicates the content.